services:
  nginx:
    image: nginx:1.0
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress:ro
    networks:
      - inception
    restart: unless-stopped

  mariadb:
    image: mariadb:1.0
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    image: wordpress:1.0
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nabboud/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nabboud/data/wordpress

secrets:
  db_root_password:
    file: ./secrets/db_root_password
  db_password:
    file: ./secrets/db_password
  wp_admin_password:
    file: ./secrets/wp_admin_password
  wp_user_password:
    file: ./secrets/wp_user_password